# Generated by Django 4.0.10 on 2023-10-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='prince',
            field=models.FloatField(default=0),
        ),
    ]
